# Generated by Django 3.1.3 on 2021-01-01 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201231_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 6, 58, 55, 577135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 1, 6, 58, 55, 576135, tzinfo=utc)),
        ),
    ]
