# Generated by Django 3.1.3 on 2021-01-01 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201231_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 7, 1, 10, 631960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 1, 7, 1, 10, 631960, tzinfo=utc)),
        ),
    ]
